---
- name: Create VSCode config
  template:
    src: "{{ dotfiles_dir }}/vscode/settings.json"
    dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/settings.json
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: Create VSCode keybindings
  template:
    src: "{{ dotfiles_dir }}/vscode/keybindings.json"
    dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/keybindings.json
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: Install VSCode Extensions
  shell: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"